export const QUESTION_RESPONSE_CODE__SUCCESS = 0;
export const QUESTION_RESPONSE_CODE__NO_RESULT = 1;
export const QUESTION_RESPONSE_CODE__INVALID_PARAMS = 2;
export const QUESTION_RESPONSE_CODE__TOKEN_NOT_FOUND = 3;
export const QUESTION_RESPONSE_CODE__TOKEN_EMPTY = 4;

export const QUESTION_RESPONSE_CODES = [
  QUESTION_RESPONSE_CODE__SUCCESS,
  QUESTION_RESPONSE_CODE__NO_RESULT,
  QUESTION_RESPONSE_CODE__INVALID_PARAMS,
  QUESTION_RESPONSE_CODE__TOKEN_NOT_FOUND,
  QUESTION_RESPONSE_CODE__TOKEN_EMPTY,
] as const;

export const QUESTION_LAST_STEP = 10;
export const QUESTION_RESULTS_LOCALSTORAGE_KEY = "QUESTION_RESULTS_LOCALSTORAGE_KEY";

export const QUIZ_START_TIME_LOCALSTORAGE_KEY = "QUIZ_START_TIME_LOCALSTORAGE_KEY";
export const QUIZ_END_TIME_LOCALSTORAGE_KEY = "QUIZ_END_TIME_LOCALSTORAGE_KEY";
