export const QUESTION_RESPONCE_CODE__SUCCESS = 0;
export const QUESTION_RESPONCE_CODE__NO_RESULT = 1;
export const QUESTION_RESPONCE_CODE__INVALID_PARAMS = 2;
export const QUESTION_RESPONCE_CODE__TOKEN_NOT_FOUND = 3;
export const QUESTION_RESPONCE_CODE__TOKEN_EMPTY = 4;

export const QUESTION_RESPONCE_CODES = [
  QUESTION_RESPONCE_CODE__SUCCESS,
  QUESTION_RESPONCE_CODE__NO_RESULT,
  QUESTION_RESPONCE_CODE__INVALID_PARAMS,
  QUESTION_RESPONCE_CODE__TOKEN_NOT_FOUND,
  QUESTION_RESPONCE_CODE__TOKEN_EMPTY,
] as const;

export const QUESTION_LAST_STEP = 10;
export const QUESTION_RESULTS_LOCALSTORAGE_KEY = "questionResults";
